name: Update README with Latest Blog Posts

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual runs
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fetch latest blog posts
        uses: gautamkrishnar/blog-post-workflow@1.8.8
        with:
          feed_list: "https://www.khaodoes.dev/blog.rss"
